### PR TITLE
Nivetha K S - 2nd Year CSE B 180501104

### PR DESCRIPTION
**Pull request by NivethaKS-18**

### CODE REVIEW

**Comment by bearlike** [comment]
Follow the PR naming format

**Comment by NivethaKS-18** [comment]
I have changed it.pls do check it.

**Comment by bearlike** [comment]
Kindly please delete the duplicate file 'hello.py' located in the root directory of the project.

**Comment by NivethaKS-18** [comment]
I deleted the duplicate file'hello.py'.pls do check

**Comment by bearlike** [comment]
✅ Looks all good!

**Review by bearlike — APPROVED** [review]

**Pull request merged**
