### PR TITLE
Srivatsan V - 2nd Year CSE C 180501147

### PR DESCRIPTION
**Pull request by srivatsannn**

### CODE REVIEW

**Comment by bearlike** [comment]
Why do you have two accounts associated with your fork?

**Comment by srivatsannn** [comment]
It's my brother's bro.I am using his gitbash and this github profile ig the 2 goT mixed

**Comment by bearlike** [comment]
Kindly do not "mix" 2 profiles again

**Comment by srivatsannn** [comment]
Done 👍

**Pull request merged**
